### machine info
num_gpus_per_job: 1  # number of gpus each job need
num_cpus_per_job: 63  # number of cpus each job need
memory_per_job: 380  # memory requirement each job need
gpu_type: "nvidia-tesla-v100"
num_gpus_per_job: 1

### CNN model
model: models.sw_mobilenet_v2
log_dir: logs/

### data
dataset: imagenet1k
data_transforms: imagenet1k_mobile
data_loader: imagenet1k_basic
dataset_dir: /home/zzh/ImageNet-Traffic/
dataset_dir: /home/zzh/2021TMC/stanford_cars
data_loader_workers: 62

###Clustering
eps: 0.00001

### info
num_classes: 196
image_size: 224
topk: [1, 5]
num_epochs: 100

### optimizer
optimizer: sgd
momentum: 0.9
weight_decay: 0.0001
nesterov: True
random_seed: 1995

### lr,batchsize,and epoch
# lr: 0.1
# lr_scheduler: multistep
# multistep_lr_milestones: [30, 60, 90]
# multistep_lr_gamma: 0.1
lr: 0.025
lr_scheduler: linear_decaying
batch_size: 128
num_epochs: 500


### pretrain, resume, test_only
pretrained: ''
resume: ''
test_only: True
reset_parameters: True


### The compression setup space
width_mult: 1.0
quant_list: [65535,255,15,3,1]
num_list: [0.03125,0.0625,0.09375,0.1250,0.15625, 0.1875, 0.21875, 0.2500, 0.5000,1.0]

### Clustering method divides the compression setup space into 3 cluster



# quant_list: [65535,255,127,63,31,15,7,3,1]
# num_list: [0.03125, 0.0625, 0.09375, 0.125, 0.15625, 0.1875, 0.21875, 0.25, 0.28125, 0.3125, 0.34375, 0.375, 0.40625, 0.4375, 0.46875, 0.5, 0.53125, 0.5625, 0.59375, 0.625, 0.65625, 0.6875, 0.71875, 0.75, 0.78125, 0.8125, 0.84375, 0.875, 0.90625, 0.9375, 0.96875, 1.0]

### Initialization method gets the teach model
initialization_model: ./logs/initialization_model.pt

### test the SW-CNN
test_only: False
#test_model: ./logs/initialization_model.pt

