### machine info
num_gpus_per_job: 4  # number of gpus each job need
num_cpus_per_job: 63  # number of cpus each job need
memory_per_job: 380  # memory requirement each job need
gpu_type: "nvidia-tesla-v100"
num_gpus_per_job: 1

### CNN model
model: models.sw_mobilenet_v2
log_dir: logs/

### data
dataset: imagenet1k
data_transforms: imagenet1k_mobile
data_loader: imagenet1k_basic
dataset_dir: /home/zzh/2021TMC/stanford_cars/
data_loader_workers: 62

###Clustering
eps: 0.00001

### info
num_classes: 196
image_size: 224
topk: [1, 5]
num_epochs: 100

### optimizer
optimizer: sgd
momentum: 0.9
weight_decay: 0.0001
nesterov: True
random_seed: 1995

### lr,batchsize,and epoch
# lr: 0.1
# lr_scheduler: multistep
# multistep_lr_milestones: [30, 60, 90]
# multistep_lr_gamma: 0.1
lr: 0.025
lr_scheduler: linear_decaying
batch_size: 128
num_epochs: 500


### pretrain, resume, test_only
pretrained: ''
resume: ''
test_only: False
reset_parameters: True


### The compression setup space
width_mult: 1.0
quant_list: [65535,255,15,3,1]
num_list: [0.03125,0.0625,0.09375,0.1250,0.15625, 0.1875, 0.21875, 0.2500, 0.5000,1.0]
test_compression_setups_intraining: [[1.0,255],[0.03125,1]]

### Clustering method divides the compression setup space into 3 cluster
cluster_set: [[[1.0, 255], [1.0, 15], [1.0, 3], [1.0, 1], [0.5, 255], [0.5, 15], [0.5, 3], [0.5, 1], [0.25, 255], [0.25, 15], [0.25, 3], [0.25, 1]],
[[0.21875, 3], [0.21875, 1], [0.1875, 3], [0.1875, 1], [0.15625, 3], [0.15625, 1], [0.125, 3], [0.125, 1], [0.09375, 3], [0.09375, 1], [0.0625, 3], [0.0625, 1], [0.03125, 3], [0.03125, 1]],
[[0.21875, 255], [0.21875, 15], [0.1875, 255], [0.1875, 15], [0.15625, 255], [0.15625, 15], [0.125, 255], [0.125, 15], [0.09375, 255], [0.09375, 15], [0.0625, 255], [0.0625, 15], [0.03125, 255], [0.03125, 15]]]


### Initialization method gets the teach model
initialization_model: ./logs/initialization_model.pt


### test the SW-CNN
<<<<<<< HEAD
test_only: True
=======
test_only: False
>>>>>>> add and modify
test_model: ./logs/best_model.pt

