### machine info
num_gpus_per_job: 1  # number of gpus each job need
num_cpus_per_job: 21  # number of cpus each job need
memory_per_job: 380  # memory requirement each job need
gpu_type: "nvidia-tesla-v100"
num_gpus_per_job: 1

### CNN model
# model: models.sw_mobilenet_v2
model: models.clio_mobilenetv2
log_dir: logs/
pretrained: False 
#use_random_connect=args.use_random_connect,
split_point: 0


### data
dataset: imagenet1k
data_transforms: imagenet1k_mobile
data_loader: imagenet1k_basic
dataset_dir: ****
data_loader_workers: 20

###Clustering
eps: 0.00001

### info
num_classes: 196
image_size: 224
topk: [1, 5]
num_epochs: 100

### optimizer
optimizer: sgd
momentum: 0.9
weight_decay: 0.0001
nesterov: True
random_seed: 1995

### lr,batchsize,and epoch
lr: 0.1
lr_scheduler: linear_decaying
batch_size: 256
num_epochs: 1000


### pretrain, resume, test_only
pretrained: ''
resume: ''
reset_parameters: True


### The compression setup space
width_mult: 1.0
quant_list: [65535,255,15,3,1]
num_list: [1,2,4,8,16,32]

### test the SW-CNN
test_only: True
test_model: ./logs/initialization_model.pt

